#!/bin/bash

# This script will run assemble.sh for a MaSuRca run and collect some stats
# plus do some other work

# CSV output to STDOUT: "(Real Time), (num contigs), (N50), (largest contig),
#    (total length)"

TIMER=/usr/bin/time
QUAST=/home/ubuntu/src/quast-5.0.2/quast.py

STDOUT_FILE="console-output.txt"
DATA_FILE="data.csv"

#-------------------------------------------------------------------------------

# Start by acctually running assemble.sh
START_TIME=$(date +"%s")
($TIMER -f "%E," ./assemble.sh > $STDOUT_FILE) &> $DATA_FILE

# Helper function pulls a time from the stdout file
function extract-time {
  grep $1 $STDOUT_FILE | grep -oP "(?<=\[).*(?=])"
}

function subtime {
  T=$(extract-time $1)
  T=$(date +"%s" -d $T)
  echo (( T - START_TIME ))
}

{ subtime "Creating mer database for Quorum"; echo ",";
  subtime "Running mega-reads correction/assembly"; echo ",";
  subtime "Estimating genome size"; echo ",";
  subtime "Running mega-reads correction/assembly"; echo ",";
  subtime "Running assembly with Flye"; echo ","; } >> $DATA_FILE

#-------------------------------------------------------------------------------

# Run a quast report, don't let it write it's logs to stdout tho
$QUAST flye/assembly.fasta &> /dev/null

# Helper function greps the latest quast report in the current directory for
# the number that falls directly after the argument
function quast-stat {
  grep -oP "(?<=$1\t)[0-9]+" quast_results/latest/report.tsv
}

# Add the relevant stats to the datafile csv
{ quast-stat "# contigs"; echo ",";
  quast-stat "N50"; echo ",";
  quast-stat "Largest contig"; echo ",";
  quast-stat "Total length"; } >> $DATA_FILE

# Write everything out of the data file to stdout, with newlines removed
tr -d '\n' < $DATA_FILE
