#!/bin/bash

# This script will run assemble.sh for a MaSuRca run and collect some stats
# plus do some other work

# CSV output to STDOUT: "(Real Time), (Memory Usage), (Size)

TIMER=/usr/bin/time
QUAST=/home/ubuntu/src/quast-5.0.2/quast.py

STDOUT_FILE="console-output.txt"
DATA_FILE="data.csv"

($TIMER -f "%E , %K ," ./assemble.sh > $STDOUT_FILE) &> $DATA_FILE

$QUAST flye/assembly.fasta

function quast-stat {
  grep -oP "(?<=$1\t)[0-9]+" quast_results/latest/report.tsv
}

quast-stat "# contigs" >> $DATA_FILE
echo "," >> $DATA_FILE
quast-stat "N50" >> $DATA_FILE
echo "," >> $DATA_FILE
quast-stat "Largest contig" >> $DATA_FILE
echo "," >> $DATA_FILE
quast-stat "Total length" >> $DATA_FILE

tr -d '\n' < $DATA_FILE
